import json
import math
from pathlib import Path
from typing import Any, Dict, List

import joblib
import pandas as pd
from fpdf import FPDF
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = PROJECT_ROOT / "data" / "water_potability.csv"
MODEL_PATH = PROJECT_ROOT / "model" / "water_quality_model.pkl"
HISTORY_PATH = PROJECT_ROOT / "data" / "prediction_history.csv"

FEATURE_COLUMNS = [
    "ph",
    "Hardness",
    "Solids",
    "Chloramines",
    "Sulfate",
    "Conductivity",
    "Organic_carbon",
    "Trihalomethanes",
    "Turbidity",
]
TARGET_COLUMN = "Potability"

INPUT_RANGES = {
    "ph": (0.0, 14.0),
    "Hardness": (0.0, 500.0),
    "Solids": (0.0, 100000.0),
    "Chloramines": (0.0, 20.0),
    "Sulfate": (0.0, 1000.0),
    "Conductivity": (0.0, 2000.0),
    "Organic_carbon": (0.0, 50.0),
    "Trihalomethanes": (0.0, 300.0),
    "Turbidity": (0.0, 20.0),
}


def get_project_root() -> Path:
    return PROJECT_ROOT


def load_css() -> None:
    css_path = PROJECT_ROOT / "assets" / "style.css"
    if css_path.exists():
        with open(css_path, "r", encoding="utf-8") as handle:
            css = handle.read()
        if st.session_state.get("theme_mode", False):
            css += """
            .stApp, [data-testid=\"stMain\"] { background: #102331; color: #e7f3f2; }
            .section-card, .metric-card, .stMetric { background: #183342; border-color: #2c5361; color: #e7f3f2; }
            h1, h2, h3, p, li, label { color: #e7f3f2; }
            """
        st.markdown(f"""
        <style>
        {css}
        </style>
        """, unsafe_allow_html=True)


def get_theme_class() -> str:
    return "dark-card" if st.session_state.get("theme_mode", True) else "card"


def ensure_data_exists() -> None:
    if not DATA_PATH.exists():
        raise FileNotFoundError(f"Dataset not found at {DATA_PATH}")


@st.cache_resource
def load_model_bundle() -> Dict[str, Any]:
    ensure_data_exists()
    if not MODEL_PATH.exists():
        raise FileNotFoundError("Model artifact not found. Run train_model.py first.")
    return joblib.load(MODEL_PATH)


def risk_level(probability: float) -> str:
    if probability >= 0.75:
        return "Low"
    if probability >= 0.55:
        return "Medium"
    return "High"


def recommendation(label: int, probability: float) -> str:
    if label == 1:
        return "The water sample appears safe for drinking. Continue routine monitoring and keep records updated."
    if probability >= 0.65:
        return "The sample is likely unsafe. Treat the water before consumption and retest promptly."
    return "The sample is unsafe. Avoid drinking it until proper water treatment and verification are completed."


def validate_user_inputs(values: Dict[str, Any]) -> List[str]:
    errors = []
    for key, value in values.items():
        try:
            numeric_value = float(value)
        except (TypeError, ValueError):
            errors.append(f"{key} must be numeric.")
            continue

        if not math.isfinite(numeric_value):
            errors.append(f"{key} must be a finite number.")
            continue

        if key in INPUT_RANGES:
            minimum, maximum = INPUT_RANGES[key]
            if not minimum <= numeric_value <= maximum:
                errors.append(f"{key} must be between {minimum:g} and {maximum:g}.")
    return errors


def save_prediction_history(record: Dict[str, Any]) -> None:
    HISTORY_PATH.parent.mkdir(parents=True, exist_ok=True)
    if HISTORY_PATH.exists():
        history = pd.read_csv(HISTORY_PATH)
    else:
        history = pd.DataFrame(columns=["Timestamp", *FEATURE_COLUMNS, "Prediction", "Confidence", "Risk", "Recommendation"])
    row = pd.DataFrame([record])
    history = pd.concat([history, row], ignore_index=True)
    history.to_csv(HISTORY_PATH, index=False)


def load_prediction_history() -> pd.DataFrame:
    if HISTORY_PATH.exists():
        return pd.read_csv(HISTORY_PATH)
    return pd.DataFrame(columns=["Timestamp", *FEATURE_COLUMNS, "Prediction", "Confidence", "Risk", "Recommendation"])


def create_pdf_report(result: Dict[str, Any]) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Water Quality Prediction Report", ln=True, align="C")
    pdf.ln(5)
    pdf.set_font("Helvetica", size=12)
    pdf.cell(0, 8, f"Prediction: {result['prediction']}", ln=True)
    pdf.cell(0, 8, f"Confidence: {result['confidence']:.2f}%", ln=True)
    pdf.cell(0, 8, f"Risk Level: {result['risk']}", ln=True)
    pdf.multi_cell(0, 8, f"Recommendation: {result['recommendation']}")
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 8, "Generated by the AI Water Quality Monitoring System", ln=True)
    return pdf.output(dest="S").encode("latin-1")
